export const data = JSON.parse("{\"key\":\"v-7d129068\",\"path\":\"/zh/css/flex%E5%B8%83%E5%B1%80.html\",\"title\":\"flex布局\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"flex布局\",\"tags\":[\"CSS\"],\"categories\":[\"重要笔记\"],\"summary\":\"在父级盒子开启flex布局 设置主轴方向 主轴分布 侧轴分布 整体多行布局 子盒子是否换行 属性解释 flexbox 对Flex容器设置display:flex或者display:inline-flex ### flex-direction 控制Flex项目沿着主轴（Main Axis）(父容器) 的排列方向 ### flex-wrap 控制Flex项目是否\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/My_blogs/zh/css/flex%E5%B8%83%E5%B1%80.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mr.冰的前端\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"flex布局\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"CSS\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-07-17T16:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"设置主轴方向\",\"slug\":\"设置主轴方向\",\"link\":\"#设置主轴方向\",\"children\":[]},{\"level\":2,\"title\":\"主轴分布\",\"slug\":\"主轴分布\",\"link\":\"#主轴分布\",\"children\":[]},{\"level\":2,\"title\":\"侧轴分布\",\"slug\":\"侧轴分布\",\"link\":\"#侧轴分布\",\"children\":[]},{\"level\":2,\"title\":\"整体多行布局\",\"slug\":\"整体多行布局\",\"link\":\"#整体多行布局\",\"children\":[]},{\"level\":2,\"title\":\"子盒子是否换行\",\"slug\":\"子盒子是否换行\",\"link\":\"#子盒子是否换行\",\"children\":[]},{\"level\":2,\"title\":\"属性解释\",\"slug\":\"属性解释\",\"link\":\"#属性解释\",\"children\":[{\"level\":3,\"title\":\"flexbox\",\"slug\":\"flexbox\",\"link\":\"#flexbox\",\"children\":[]},{\"level\":3,\"title\":\"flex-direction\",\"slug\":\"flex-direction\",\"link\":\"#flex-direction\",\"children\":[]},{\"level\":3,\"title\":\"flex-wrap\",\"slug\":\"flex-wrap\",\"link\":\"#flex-wrap\",\"children\":[]},{\"level\":3,\"title\":\"flex-flow\",\"slug\":\"flex-flow\",\"link\":\"#flex-flow\",\"children\":[]},{\"level\":3,\"title\":\"justify-content\",\"slug\":\"justify-content\",\"link\":\"#justify-content\",\"children\":[]},{\"level\":3,\"title\":\"align-items\",\"slug\":\"align-items\",\"link\":\"#align-items\",\"children\":[]},{\"level\":3,\"title\":\"align-content\",\"slug\":\"align-content\",\"link\":\"#align-content\",\"children\":[]},{\"level\":3,\"title\":\"order\",\"slug\":\"order\",\"link\":\"#order\",\"children\":[]},{\"level\":3,\"title\":\"flex-basis\",\"slug\":\"flex-basis\",\"link\":\"#flex-basis\",\"children\":[]},{\"level\":3,\"title\":\"flex-grow\",\"slug\":\"flex-grow\",\"link\":\"#flex-grow\",\"children\":[]},{\"level\":3,\"title\":\"flex-shrink\",\"slug\":\"flex-shrink\",\"link\":\"#flex-shrink\",\"children\":[]},{\"level\":3,\"title\":\"align-self\",\"slug\":\"align-self\",\"link\":\"#align-self\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.16,\"words\":949},\"filePathRelative\":\"zh/css/flex布局.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
