export const data = JSON.parse("{\"key\":\"v-c5ffdcd4\",\"path\":\"/zh/js/TypeScript.html\",\"title\":\"TypeScript\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"TypeScript\",\"date\":\"2022-07-19T00:00:00.000Z\",\"tags\":[\"JS\"],\"summary\":\"类型注解 数组 Object 元祖类型 枚举 函数类型 泛型 📌 可以通过T指定调用的时候再确定类型 any 📌 any不会做任何类型检查，语法不会报错 类型断言 自己指定执行的结果类型 interface接口 接口可选成员&只读成员 📌 ？可选成员 📌 readonly 只读成员 类 类-访问修饰符 类-只读属性 类与接口 抽象类 泛型 类型声明 \",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/My_blogs/zh/js/TypeScript.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mr.冰的前端\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"TypeScript\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"JS\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-07-19T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"类型注解\",\"slug\":\"类型注解\",\"link\":\"#类型注解\",\"children\":[]},{\"level\":2,\"title\":\"数组\",\"slug\":\"数组\",\"link\":\"#数组\",\"children\":[]},{\"level\":2,\"title\":\"Object\",\"slug\":\"object\",\"link\":\"#object\",\"children\":[]},{\"level\":2,\"title\":\"枚举\",\"slug\":\"枚举\",\"link\":\"#枚举\",\"children\":[]},{\"level\":2,\"title\":\"函数类型\",\"slug\":\"函数类型\",\"link\":\"#函数类型\",\"children\":[]},{\"level\":2,\"title\":\"泛型\",\"slug\":\"泛型\",\"link\":\"#泛型\",\"children\":[]},{\"level\":2,\"title\":\"any\",\"slug\":\"any\",\"link\":\"#any\",\"children\":[]},{\"level\":2,\"title\":\"interface接口\",\"slug\":\"interface接口\",\"link\":\"#interface接口\",\"children\":[]},{\"level\":2,\"title\":\"接口可选成员&只读成员\",\"slug\":\"接口可选成员-只读成员\",\"link\":\"#接口可选成员-只读成员\",\"children\":[]},{\"level\":2,\"title\":\"类\",\"slug\":\"类\",\"link\":\"#类\",\"children\":[]},{\"level\":2,\"title\":\"类-只读属性\",\"slug\":\"类-只读属性\",\"link\":\"#类-只读属性\",\"children\":[]},{\"level\":2,\"title\":\"类与接口\",\"slug\":\"类与接口\",\"link\":\"#类与接口\",\"children\":[]},{\"level\":2,\"title\":\"抽象类\",\"slug\":\"抽象类\",\"link\":\"#抽象类\",\"children\":[]},{\"level\":2,\"title\":\"泛型\",\"slug\":\"泛型-1\",\"link\":\"#泛型-1\",\"children\":[]},{\"level\":2,\"title\":\"类型声明\",\"slug\":\"类型声明\",\"link\":\"#类型声明\",\"children\":[]},{\"level\":2,\"title\":\"7隐式类型推断\",\"slug\":\"_7隐式类型推断\",\"link\":\"#_7隐式类型推断\",\"children\":[]},{\"level\":2,\"title\":\"tsconfig.json文件说明\",\"slug\":\"tsconfig-json文件说明\",\"link\":\"#tsconfig-json文件说明\",\"children\":[]}],\"readingTime\":{\"minutes\":4.91,\"words\":1472},\"filePathRelative\":\"zh/js/TypeScript.md\",\"localizedDate\":\"2022年7月19日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
